apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: lengthy-cicada-java-springboot
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:cb42b245e52d5af2a8ec2c913afbbb2d75f14fb1@sha256:92459a9f242f1301a19f094577e0f2a2ef38dc1419f3820bd253a5300fa9a2c9
        name: container-image  
